<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\eventstore\\emptyeventscollectionexception' => '/old/EmptyEventsCollectionException.php',
                'spriebsch\\eventstore\\eventreader' => '/old/EventReader.php',
                'spriebsch\\eventstore\\events' => '/Events.php',
                'spriebsch\\eventstore\\failedtostoreeventexception' => '/old/FailedToStoreEventException.php',
                'spriebsch\\eventstore\\failedtostoreeventforunknownreasonexception' => '/old/FailedToStoreEventForUnknownReasonException.php',
                'spriebsch\\eventstore\\sqliteeventreader' => '/old/SqliteEventReader.php',
                'spriebsch\\eventstore\\sqliteeventwriter' => '/SqliteEventWriter.php',
                'spriebsch\\sequora\\databasewriter' => '/database/DatabaseWriter.php',
                'spriebsch\\sequora\\eventwriter' => '/EventWriter.php',
                'spriebsch\\sequora\\sequorawriter' => '/SequoraWriter.php',
                'spriebsch\\sequora\\sqlitedatabasewriter' => '/database/sqlite/SqliteDatabaseWriter.php',
                'spriebsch\\sequora\\sqlitesequoraschema' => '/database/sqlite/SqliteSequoraSchema.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
