<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\sequora\\binaryuuid' => '/BinaryUUID.php',
                'spriebsch\\sequora\\databasereader' => '/database/DatabaseReader.php',
                'spriebsch\\sequora\\databasewriter' => '/database/DatabaseWriter.php',
                'spriebsch\\sequora\\eventquery' => '/EventQuery.php',
                'spriebsch\\sequora\\eventquerysqlitesqlbuilder' => '/database/sqlite/EventQuerySqliteSqlBuilder.php',
                'spriebsch\\sequora\\eventreader' => '/EventReader.php',
                'spriebsch\\sequora\\events' => '/events/Events.php',
                'spriebsch\\sequora\\eventwriter' => '/EventWriter.php',
                'spriebsch\\sequora\\failedtostoreeventexception' => '/database/FailedToStoreEventException.php',
                'spriebsch\\sequora\\failedtostoreeventforunknownreasonexception' => '/database/FailedToStoreEventForUnknownReasonException.php',
                'spriebsch\\sequora\\noeventsexception' => '/events/NoEventsException.php',
                'spriebsch\\sequora\\sequoraexception' => '/SequoraException.php',
                'spriebsch\\sequora\\sequorareader' => '/SequoraReader.php',
                'spriebsch\\sequora\\sequorawriter' => '/SequoraWriter.php',
                'spriebsch\\sequora\\sqlitedatabasereader' => '/database/sqlite/SqliteDatabaseReader.php',
                'spriebsch\\sequora\\sqlitedatabasewriter' => '/database/sqlite/SqliteDatabaseWriter.php',
                'spriebsch\\sequora\\sqlitesequoraschema' => '/database/sqlite/SqliteSequoraSchema.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
