<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\eventstore\\emptyeventscollectionexception' => '/EmptyEventsCollectionException.php',
                'spriebsch\\eventstore\\eventreader' => '/EventReader.php',
                'spriebsch\\eventstore\\events' => '/Events.php',
                'spriebsch\\eventstore\\failedtostoreeventexception' => '/FailedToStoreEventException.php',
                'spriebsch\\eventstore\\failedtostoreeventforunknownreasonexception' => '/FailedToStoreEventForUnknownReasonException.php',
                'spriebsch\\eventstore\\sqliteeventreader' => '/SqliteEventReader.php',
                'spriebsch\\eventstore\\sqliteeventwriter' => '/SqliteEventWriter.php',
                'spriebsch\\projecttemplate\\helloworld' => '/HelloWorld.php',
                'spriebsch\\sequora\\databasewriter' => '/DatabaseWriter.php',
                'spriebsch\\sequora\\eventwriter' => '/EventWriter.php',
                'spriebsch\\sequora\\sequorawriter' => '/EventStoreWriter.php',
                'spriebsch\\sequora\\sqlitesequoraschema' => '/SqliteSequoraSchema.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
